made pipeline fail on maven test failure not just error

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -384,9 +384,9 @@ jobs:
           testspace "[junit/camel]junit/camel/junit.log{$(cat junit/camel/junit.exit-code):jav 14 camel junit tests}"           # upload camel log with exit code      
       - name: assert success
         run: |
-          if [ $(cat junit/commons/junit.exit-code) != 0 ]; then cat junit/commons/junit.log && exit 1; fi        # print commons log and exit if foo failed
-          if [ $(cat junit/backend/junit.exit-code) != 0 ]; then cat junit/backend/junit.log && exit 1; fi        # print backend log and exit if foo failed
-          if [ $(cat junit/camel/junit.exit-code) != 0 ]; then cat junit/camel/junit.log && exit 1; fi            # print camel log and exit if foo failed
+          if [ $(cat junit/commons/junit.exit-code) != 0 ] || [ $(cat junit/commons/junit.mvn.exit-code) != 0 ]; then cat junit/commons/junit.log && exit 1; fi      # print commons log and exit if commons failed
+          if [ $(cat junit/backend/junit.exit-code) != 0 ] || [ $(cat junit/backend/junit.mvn.exit-code) != 0 ]; then cat junit/backend/junit.log && exit 1; fi      # print backend log and exit if backend failed
+          if [ $(cat junit/camel/junit.exit-code) != 0 ] || [ $(cat junit/camel/junit.mvn.exit-code) != 0 ]; then cat junit/camel/junit.log && exit 1; fi            # print camel log and exit if camel failed
       - uses: actions/upload-artifact@v3
         if: failure()
         with:
